import BlockToolData as Type
vite v4.0.4 building for production...
node_modules/@editorjs/editorjs/types/configs/conversion-config.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' 

1 import {BlockToolData} from '../tools';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@editorjs/editorjs/types/configs/conversion-config.ts:1:9 - error TS1444: 'BlockToolData' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import {BlockToolData} from '../tools';